import 'package:flutter/material.dart';

class Recommendedmodel{
  dynamic images;
  String hotelname;
  String cont1;
  String cont2;
  String cont3;
  String Address;
  String Star;
  String tym;
  dynamic images2;
  

   Recommendedmodel({
    required this.images,
    required this.hotelname,
    required this.cont1,
    required this.cont2,
    required this.cont3,
    required this.Address,
    required this.Star,
    required this.tym,
    required this.images2,

   });
}

List Recommendedmodellist=[
  Recommendedmodel(images: "assets/images/resto1.png", 
  hotelname: "Fire Wings", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto1a.png", 
  hotelname: "Bhiwandi Darbar", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto2.png", 
  hotelname: "Mamaji Pavbhaji", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto2a.png", 
  hotelname: "Anna’s Kitchen", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto3.png", 
  hotelname: "A-1 Seekh Paratha", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto1.png", 
  hotelname: "Fire Wings", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto1a.png", 
  hotelname: "Bhiwandi Darbar", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto2.png", 
  hotelname: "Mamaji Pavbhaji", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto2a.png", 
  hotelname: "Anna’s Kitchen", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto3.png", 
  hotelname: "A-1 Seekh Paratha", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto2a.png", 
  hotelname: "Anna’s Kitchen", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
  Recommendedmodel(images: "assets/images/resto3.png", 
  hotelname: "A-1 Seekh Paratha", 
  cont1: "Burger", 
  cont2: "Pizza", 
  cont3: "Wings", 
  Address: "Near Hafiz Baba Dargah", 
  Star: "4.3", 
  tym: "30 mins  •  ₹230 for two  ",
  images2: ""),
];